INSERT INTO leagues(league_name, rank, country) VALUES ('pretium aliquet, metus',4,42);
INSERT INTO leagues(league_name, rank, country) VALUES ('gravida',4,77);
INSERT INTO leagues(league_name, rank, country) VALUES ('justo.',3,222);
INSERT INTO leagues(league_name, rank, country) VALUES ('egestas hendrerit neque.',3,218);
INSERT INTO leagues(league_name, rank, country) VALUES ('diam at pretium',5,88);
INSERT INTO leagues(league_name, rank, country) VALUES ('Praesent eu',1,204);
INSERT INTO leagues(league_name, rank, country) VALUES ('arcu.',5,62);
INSERT INTO leagues(league_name, rank, country) VALUES ('viverra. Donec tempus,',1,15);
INSERT INTO leagues(league_name, rank, country) VALUES ('Proin velit. Sed',3,192);
INSERT INTO leagues(league_name, rank, country) VALUES ('tellus,',5,114);
INSERT INTO leagues(league_name, rank, country) VALUES ('est ac facilisis',3,73);
INSERT INTO leagues(league_name, rank, country) VALUES ('nisl. Maecenas',5,41);
INSERT INTO leagues(league_name, rank, country) VALUES ('vitae erat vel',2,198);
INSERT INTO leagues(league_name, rank, country) VALUES ('ac ipsum.',4,184);
INSERT INTO leagues(league_name, rank, country) VALUES ('Sed',3,29);
INSERT INTO leagues(league_name, rank, country) VALUES ('Duis',3,177);
INSERT INTO leagues(league_name, rank, country) VALUES ('Nunc pulvinar',4,229);
INSERT INTO leagues(league_name, rank, country) VALUES ('amet, dapibus id,',5,13);
INSERT INTO leagues(league_name, rank, country) VALUES ('pharetra. Nam',5,233);
INSERT INTO leagues(league_name, rank, country) VALUES ('eu',4,184);
INSERT INTO leagues(league_name, rank, country) VALUES ('a, malesuada id,',4,221);
INSERT INTO leagues(league_name, rank, country) VALUES ('risus. Nunc ac',5,178);
INSERT INTO leagues(league_name, rank, country) VALUES ('viverra. Donec',6,83);
INSERT INTO leagues(league_name, rank, country) VALUES ('laoreet lectus',6,89);
INSERT INTO leagues(league_name, rank, country) VALUES ('quis',4,37);
INSERT INTO leagues(league_name, rank, country) VALUES ('vulputate dui,',1,192);
INSERT INTO leagues(league_name, rank, country) VALUES ('nunc est, mollis',2,41);
INSERT INTO leagues(league_name, rank, country) VALUES ('sagittis',1,7);
INSERT INTO leagues(league_name, rank, country) VALUES ('ipsum ac',1,235);
INSERT INTO leagues(league_name, rank, country) VALUES ('molestie in,',4,153);
INSERT INTO leagues(league_name, rank, country) VALUES ('at',3,45);
INSERT INTO leagues(league_name, rank, country) VALUES ('Nulla facilisi. Sed',1,135);
INSERT INTO leagues(league_name, rank, country) VALUES ('enim. Mauris',5,242);
INSERT INTO leagues(league_name, rank, country) VALUES ('nisl elementum purus,',4,47);
INSERT INTO leagues(league_name, rank, country) VALUES ('bibendum',2,13);
INSERT INTO leagues(league_name, rank, country) VALUES ('luctus. Curabitur',1,151);
INSERT INTO leagues(league_name, rank, country) VALUES ('blandit enim',4,178);
INSERT INTO leagues(league_name, rank, country) VALUES ('risus.',6,199);
INSERT INTO leagues(league_name, rank, country) VALUES ('at, nisi.',5,187);
INSERT INTO leagues(league_name, rank, country) VALUES ('Sed nec metus',1,34);
INSERT INTO leagues(league_name, rank, country) VALUES ('vel',2,42);
INSERT INTO leagues(league_name, rank, country) VALUES ('augue ac ipsum.',6,74);
INSERT INTO leagues(league_name, rank, country) VALUES ('ornare, elit',4,82);
INSERT INTO leagues(league_name, rank, country) VALUES ('orci.',5,78);
INSERT INTO leagues(league_name, rank, country) VALUES ('dignissim',6,192);
INSERT INTO leagues(league_name, rank, country) VALUES ('arcu. Aliquam ultrices',4,195);
INSERT INTO leagues(league_name, rank, country) VALUES ('luctus, ipsum',3,210);
INSERT INTO leagues(league_name, rank, country) VALUES ('nibh. Phasellus',1,203);
INSERT INTO leagues(league_name, rank, country) VALUES ('fringilla.',6,93);
INSERT INTO leagues(league_name, rank, country) VALUES ('ac libero',6,32);
INSERT INTO leagues(league_name, rank, country) VALUES ('ut',5,183);
INSERT INTO leagues(league_name, rank, country) VALUES ('fermentum convallis ligula.',6,25);
INSERT INTO leagues(league_name, rank, country) VALUES ('arcu iaculis',3,128);
INSERT INTO leagues(league_name, rank, country) VALUES ('Cras',2,124);
INSERT INTO leagues(league_name, rank, country) VALUES ('pretium',2,237);
INSERT INTO leagues(league_name, rank, country) VALUES ('pretium',4,27);
INSERT INTO leagues(league_name, rank, country) VALUES ('et, commodo',2,84);
INSERT INTO leagues(league_name, rank, country) VALUES ('Aliquam',6,235);
INSERT INTO leagues(league_name, rank, country) VALUES ('sed sem',5,110);
INSERT INTO leagues(league_name, rank, country) VALUES ('et ultrices',2,70);
INSERT INTO leagues(league_name, rank, country) VALUES ('auctor vitae, aliquet',6,203);
INSERT INTO leagues(league_name, rank, country) VALUES ('tempor augue ac',5,244);
INSERT INTO leagues(league_name, rank, country) VALUES ('Mauris eu',5,132);
INSERT INTO leagues(league_name, rank, country) VALUES ('Aenean euismod',6,44);
INSERT INTO leagues(league_name, rank, country) VALUES ('Duis',4,43);
INSERT INTO leagues(league_name, rank, country) VALUES ('enim, condimentum eget,',5,201);
INSERT INTO leagues(league_name, rank, country) VALUES ('nascetur',4,114);
INSERT INTO leagues(league_name, rank, country) VALUES ('Curabitur egestas',4,219);
INSERT INTO leagues(league_name, rank, country) VALUES ('dapibus ligula. Aliquam',6,224);
INSERT INTO leagues(league_name, rank, country) VALUES ('eu',2,111);
INSERT INTO leagues(league_name, rank, country) VALUES ('commodo',6,21);
INSERT INTO leagues(league_name, rank, country) VALUES ('posuere, enim',4,66);
INSERT INTO leagues(league_name, rank, country) VALUES ('Ut sagittis',5,141);
INSERT INTO leagues(league_name, rank, country) VALUES ('sed pede. Cum',1,33);
INSERT INTO leagues(league_name, rank, country) VALUES ('Duis at lacus.',3,34);
INSERT INTO leagues(league_name, rank, country) VALUES ('non, lacinia at,',3,226);
INSERT INTO leagues(league_name, rank, country) VALUES ('felis',4,165);
INSERT INTO leagues(league_name, rank, country) VALUES ('pede nec',6,106);
INSERT INTO leagues(league_name, rank, country) VALUES ('pede.',4,177);
INSERT INTO leagues(league_name, rank, country) VALUES ('aliquam',5,101);
INSERT INTO leagues(league_name, rank, country) VALUES ('massa. Integer',1,4);
INSERT INTO leagues(league_name, rank, country) VALUES ('diam',1,125);
INSERT INTO leagues(league_name, rank, country) VALUES ('risus, at fringilla',6,159);
INSERT INTO leagues(league_name, rank, country) VALUES ('pharetra nibh. Aliquam',4,56);
INSERT INTO leagues(league_name, rank, country) VALUES ('iaculis',5,204);
INSERT INTO leagues(league_name, rank, country) VALUES ('venenatis',3,155);
INSERT INTO leagues(league_name, rank, country) VALUES ('non,',1,33);
INSERT INTO leagues(league_name, rank, country) VALUES ('nonummy ipsum',5,86);
INSERT INTO leagues(league_name, rank, country) VALUES ('rhoncus. Nullam',2,16);
INSERT INTO leagues(league_name, rank, country) VALUES ('Integer',1,6);
INSERT INTO leagues(league_name, rank, country) VALUES ('Nulla',3,165);
INSERT INTO leagues(league_name, rank, country) VALUES ('molestie.',6,43);
INSERT INTO leagues(league_name, rank, country) VALUES ('quam',2,3);
INSERT INTO leagues(league_name, rank, country) VALUES ('Nulla',3,53);
INSERT INTO leagues(league_name, rank, country) VALUES ('pellentesque a, facilisis',5,27);
INSERT INTO leagues(league_name, rank, country) VALUES ('massa.',5,227);
INSERT INTO leagues(league_name, rank, country) VALUES ('augue id',3,193);
INSERT INTO leagues(league_name, rank, country) VALUES ('turpis',4,92);
INSERT INTO leagues(league_name, rank, country) VALUES ('sem. Nulla interdum.',3,138);
INSERT INTO leagues(league_name, rank, country) VALUES ('luctus. Curabitur',5,26);