INSERT INTO "teams" (short_name,full_name,league) VALUES ('Bifrorw','In Tincidunt Congue LLP',56);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Qubyiig','Magna Corporation',56);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Vekuedt','Libero At Corp.',90);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Rummiph','Orci Limited',45);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Eowredg','Blandit Viverra Donec Consulting',39);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Yirdosi','Donec Consulting',55);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Yaeyece','Vitae Corp.',15);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Yipfiwz','Sagittis Duis Gravida Institute',11);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Oarvuah','Praesent Interdum Limited',62);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Ioxriuh','Elit Elit Fermentum LLP',33);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Yaonobm','Convallis Ante Lectus PC',87);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Bagcohd','Sodales At Limited',28);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Hooauhu','Etiam Company',28);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Geanadc','Lorem Vehicula Et Institute',8);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Mueniyx','Duis Dignissim Tempor Incorporated',55);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Quudowy','Rhoncus Proin Institute',58);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Fexlugx','At Sem Consulting',39);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Eojrulk','Eu Institute',99);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Wibcowz','Dolor Dolor Tempus Consulting',85);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Baciagw','Neque Vitae LLC',62);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Aejwajq','Justo Sit Amet Ltd',46);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Coutilc','Est Tempor Bibendum Incorporated',3);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Aahmezp','Odio Tristique Pharetra Corporation',23);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Solxobb','Elit Pharetra Limited',64);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Heyxieu','Vivamus Rhoncus Donec Foundation',24);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Yujyuiu','Enim Non Nisi Corp.',76);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Masyubr','Maecenas Mi Incorporated',43);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Yufriuh','Cras Ltd',1);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Oodrisj','Fusce Mi Institute',17);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Gotrekc','Eu Tellus Institute',59);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Ruldohn','At Auctor Ullamcorper PC',68);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Wojduzc','In Condimentum Company',25);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Yajeeys','Quisque Foundation',39);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Fenbatu','Augue Consulting',93);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Lucvobq','Iaculis Quis Corp.',60);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Youfevk','In Molestie Tortor Institute',47);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Pusmooa','Fusce Mi Lorem Limited',34);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Ioooaks','Molestie Orci Corp.',31);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Hahluto','Eu Placerat Corporation',55);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Sieqesc','Tellus Aenean Corporation',52);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Iouguiv','Scelerisque Scelerisque Dui LLP',22);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Iokiory','Massa Vestibulum Accumsan Company',57);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Oidrujn','Cum Sociis Natoque PC',39);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Wolcojh','Ultricies Limited',24);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Eobjifd','Justo Faucibus Associates',8);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Xoxnikh','Ut Dolor LLC',78);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Puluaie','Non Arcu Inc.',51);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Kikjakz','Fermentum Metus Aenean Ltd',4);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Geapajk','Luctus Ipsum Leo Corp.',78);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Culialg','Turpis LLP',42);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Tulgeid','Lectus Company',95);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Aehpuoe','Sit Amet Incorporated',42);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Ruogosv','Nibh Corporation',6);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Zoyuotw','Neque LLP',44);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Woeiagc','Lacinia Orci Corporation',10);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Bewjuef','Magna Suspendisse Tristique Limited',62);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Leboijj','Praesent Eu Nulla LLP',90);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Mijvibe','Tempor Est Ac Institute',35);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Xoufoie','Cursus Purus LLP',45);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Nibuedu','Convallis Ligula Institute',55);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Laeceqw','Cras Sed Foundation',8);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Fuiwotn','Ac Arcu Consulting',10);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Vaujach','Nulla Interdum PC',32);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Nupqeip','Egestas Hendrerit Neque Company',91);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Xozeils','Ut Cursus Luctus Foundation',21);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Damoemu','Facilisis Suspendisse Commodo Corporation',62);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Logeigz','Ut Aliquam Iaculis LLP',42);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Dobqoec','Consectetuer Rhoncus Nullam Limited',11);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Divbeok','A Felis Incorporated',70);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Jughuub','Eu Foundation',50);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Suhwozt','A Malesuada Limited',76);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Geroilf','Curabitur Vel Industries',37);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Nidlanm','Massa LLC',55);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Xaszozt','Facilisis Eget PC',96);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Saneumd','Ac Institute',32);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Vuaaijl','Mauris Incorporated',22);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Zufmugh','Ut Eros Non Consulting',20);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Geooinj','Per Conubia Foundation',19);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Zesbuos','Auctor Velit Industries',2);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Zakaarl','Eget Institute',10);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Mapbetm','Fermentum Limited',8);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Humbupp','In Felis Nulla Corp.',25);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Iiaqawj','Interdum Curabitur Dictum Consulting',99);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Jeliake','Cursus Et Eros Ltd',78);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Iuxoekm','Lectus Cum Limited',86);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Aawiiir','Aliquam Inc.',37);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Ioteufm','Dolor Nulla Corporation',97);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Sajaatm','Interdum Libero Dui Associates',81);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Pilgugl','Sociis Natoque PC',98);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Hizkeds','Tempus Scelerisque LLC',51);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Pixgipk','Elit Etiam Laoreet Institute',1);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Qetzulw','Cras Vehicula Corporation',10);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Buwpegh','Leo Cras Company',43);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Hebzifr','Leo Morbi LLP',70);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Xoliisp','Mauris Suspendisse Company',74);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Papiugd','Egestas A Institute',12);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Mirxiaj','Odio Sagittis Foundation',52);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Dalbanv','Eu Odio Tristique LLC',51);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Petzupr','Sed LLP',88);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Jeqfody','Erat Vivamus Nisi Corporation',91);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Oekuopt','Laoreet Ipsum Foundation',62);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Wujdefl','Ultricies Adipiscing Foundation',1);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Gotkerl','Duis LLC',36);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Ruphaas','Donec Limited',100);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Rojqevo','Mi Eleifend LLC',27);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Uarpipz','Ac Consulting',16);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Oefioex','Velit Pellentesque Corporation',45);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Vuhkedg','Dolor Egestas Rhoncus Consulting',16);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Rudyapo','Eu Ligula Aenean Consulting',60);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Hikkagm','Ac Arcu Nunc Corp.',89);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Qesloby','Est Mauris Rhoncus LLC',62);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Iufxozr','Lobortis PC',27);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Eazcach','Lorem Luctus Ut Industries',13);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Tuohilg','Et Rutrum Eu Foundation',61);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Jigkebj','Dolor Tempus Consulting',4);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Vitoovg','Cras Vehicula Aliquet Ltd',4);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Dabaowu','Turpis Foundation',36);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Lebaihx','Netus Et Malesuada Limited',4);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Iiheack','Nec Tempus Scelerisque Incorporated',98);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Carluco','Donec Felis Orci Corp.',96);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Neyciqc','Eu Institute',24);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Yoesohv','Lorem Ut Aliquam Limited',83);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Oijuunm','Ut PC',63);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Uuqauhd','Odio Auctor Vitae Limited',67);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Iixiojm','Ante Limited',89);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Fuibazi','Adipiscing Elit Industries',88);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Zudoepp','A Ultricies Associates',74);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Jotoucg','Blandit Congue In Consulting',80);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Kaivowv','Ipsum Phasellus Vitae Incorporated',17);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Aimbixy','Quisque Tincidunt Pede Ltd',77);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Ruauuxd','Cursus Non Egestas Corp.',54);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Iaifaft','Semper Rutrum Inc.',1);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Pokduqx','Ante Ipsum Primis Ltd',84);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Haumukp','Imperdiet Ullamcorper PC',98);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Fajnomx','Malesuada Augue Limited',29);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Aanbirn','Augue Id Foundation',66);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Qezpibq','Id Limited',91);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Vodtojl','Lorem Consulting',11);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Nuhkicu','Ad Litora Torquent Foundation',40);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Gaufatg','Sed Eu Inc.',37);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Vojnikd','At Ltd',95);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Zutxukn','Vivamus Rhoncus Donec PC',76);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Uuugasl','Pharetra Nibh Aliquam Ltd',31);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Gojceuz','Magnis Dis Ltd',75);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Yahbajj','Id LLC',63);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Aueoafg','Semper Dui Limited',72);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Fanroib','Sagittis Nullam Corporation',73);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Sekfiqd','Enim Associates',79);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Wizwiww','Donec Consectetuer Institute',2);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Cesjozr','Vitae Inc.',43);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Veemuxb','Nibh Enim Gravida Limited',35);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Tubaogj','Ante LLP',68);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Heysiwe','Lobortis Limited',60);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Faxoeel','Nullam Foundation',78);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Teiqugj','Ipsum Non Arcu Consulting',88);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Siosikr','Non Egestas LLP',10);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Rurvawp','Lorem Inc.',41);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Xaytabs','Aliquam Company',61);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Ieofemq','Dapibus Quam Quis Incorporated',97);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Mikiiim','Phasellus Institute',74);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Qaotubf','Nullam Enim Sed LLP',84);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Kouhisr','Lacus Aliquam Inc.',92);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Sinbeuh','Cum Corp.',26);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Zictudo','Accumsan Neque Corp.',70);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Oepyuzs','Ultrices Duis Volutpat LLP',18);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Sauaies','Arcu PC',9);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Mejcoiv','Leo Ltd',52);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Vuqcedn','Vel Vulputate Eu Industries',30);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Nuibopz','Adipiscing Foundation',72);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Xuueupv','Bibendum Sed Est Corp.',27);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Zoltitf','Aliquet Limited',27);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Kegnito','Arcu LLC',17);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Seffelb','Blandit PC',74);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Oomluii','Eleifend Inc.',99);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Tokeiyg','Eu Eros Nam PC',46);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Eabqicb','Orci Adipiscing Institute',15);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Peazoub','Cursus LLP',95);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Eieeiqc','Consectetuer Euismod Est Incorporated',95);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Hoehaul','Nonummy Ultricies Company',31);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Zakjezj','Neque Inc.',60);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Fiqpeve','Vel Turpis Aliquam PC',99);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Hulviaf','Duis At Lacus Associates',41);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Xooxedh','Sodales At Velit Institute',37);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Euwxauu','Etiam Institute',59);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Zazdetj','Donec Feugiat Industries',51);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Dupdewk','Risus Duis A Corp.',71);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Uuwkirb','Sed Auctor Industries',16);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Oodaiyl','Lacus Aliquam Rutrum PC',61);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Loxoizr','Ut Company',72);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Muxuepu','Aliquam Nisl Nulla Corporation',26);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Yemrauj','Enim Inc.',24);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Xirvukh','Fusce Industries',16);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Mageunq','Lectus Cum Sociis Inc.',77);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Uehcimp','Sagittis Placerat Cras Industries',85);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Begzozb','Augue LLP',24);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Wuereao','Donec Vitae Company',56);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Cooiayf','Turpis Inc.',94);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Gecduvr','Lacus Aliquam Rutrum LLP',25);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Tuihohf','Neque PC',17);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Eihiift','Felis Nulla LLP',82);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Tauvofc','Rhoncus Id Corporation',75);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Gewzauj','Faucibus Morbi Vehicula Incorporated',15);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Iukveyg','Tortor Nibh Sit LLP',3);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Qehkase','Eu Ultrices Incorporated',26);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Xeufeei','Ullamcorper Viverra Maecenas LLC',90);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Cekhomb','Velit Cras LLC',4);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Jappady','Quisque LLP',58);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Cuumodh','Neque Institute',93);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Jawrois','Non Lobortis Ltd',31);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Lioruep','Adipiscing Lacus Ut Company',72);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Cuklips','Purus Inc.',47);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Dusxajl','Malesuada Company',82);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Sijmolc','Consequat Dolor Vitae LLP',68);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Yokkoxg','Nulla LLC',46);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Zaxzakv','Elit Erat Corp.',89);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Fapgokr','Nec Urna LLC',55);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Riohipx','Vel Corporation',78);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Caubeqg','Placerat PC',2);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Yuvyiso','Mi Enim LLC',27);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Xudzipa','Velit Industries',88);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Vougaxu','At Velit Incorporated',16);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Duoxizb','Ac Company',27);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Cazuooj','Sit Amet Associates',41);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Cevcazo','In Sodales Corporation',17);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Poccoqa','Risus Quisque LLC',65);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Deaaebb','Aliquet Magna Company',53);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Buqoakd','A Tortor Nunc Company',51);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Moxzugf','Nec Tellus Nunc Foundation',15);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Yulfimp','Sed Turpis Nec Corporation',95);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Qibqomf','Vitae Diam Proin Corporation',50);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Civwins','Sit Ltd',86);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Beddevw','Nisl LLP',46);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Iopcusj','Dignissim Pharetra Nam Limited',8);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Yihioon','Elit LLP',18);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Wuacilw','Non Egestas A Limited',36);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Vizgiax','Fusce Feugiat Lorem Foundation',78);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Pucjofo','Sed Molestie LLP',35);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Cupcuiw','Eros Associates',28);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Oiscetz','Adipiscing Lobortis Risus Corp.',62);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Beggivv','Volutpat Nunc Sit Institute',89);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Huxkefx','Urna Nunc Quis PC',47);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Puseewu','Hendrerit Consectetuer Industries',56);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Jupqegv','At Libero Morbi Consulting',42);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Xieaehk','Erat Institute',82);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Iifseon','Auctor Quis Ltd',71);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Jawkeya','Lorem Ipsum Dolor Corp.',80);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Dahoefs','Etiam Laoreet LLC',63);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Auhneur','Consectetuer Rhoncus Consulting',56);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Yetkelc','Erat Vivamus Nisi Consulting',82);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Aaufalp','Ante Inc.',21);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Qeamumq','Vestibulum Nec LLP',80);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Bikmohy','Tellus Incorporated',16);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Gahaarg','Orci Tincidunt Adipiscing Associates',27);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Kehdojf','A Ltd',74);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Baqbidt','Orci Ut Corp.',14);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Wovzuwu','Augue Ut Corp.',75);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Muskifx','Aliquet Corp.',46);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Vuipemy','Dolor Fusce Incorporated',64);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Rosbuct','Nulla Company',41);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Wimrovb','Molestie Pharetra Nibh Corp.',90);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Oulyoff','Nunc Ullamcorper Inc.',30);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Lixtuqn','Integer Limited',9);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Tifkuaf','Id Corporation',37);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Auzfone','Malesuada PC',43);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Zamcuar','Curabitur Egestas Nunc Consulting',45);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Tedtovr','Non Ltd',20);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Iihqotp','Consequat Dolor Vitae Institute',32);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Weobohd','Est Incorporated',13);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Hojkeoe','Eu PC',36);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Zecaakx','Posuere Cubilia Curae; Institute',45);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Mueaotg','Adipiscing Industries',83);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Zebluiw','Nunc Corp.',18);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Yubsudg','Nec Consulting',89);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Bavzacr','Blandit Congue In LLC',40);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Bamiict','Luctus Ltd',100);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Kijbemw','Nec PC',84);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Mokmayq','Risus Corp.',53);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Diwnehv','Cras Foundation',78);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Eolwejp','Non Enim Mauris LLC',4);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Eofrufv','Donec Tempor Est Institute',22);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Negxivp','Quisque Industries',8);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Aairiym','Ut Erat Industries',13);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Xueviwe','Sed Molestie Inc.',10);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Kopserm','Pellentesque Corp.',12);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Cityarj','Quis Diam Luctus LLP',47);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Xebpack','Ligula Tortor Inc.',85);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Xokmulo','Dapibus LLC',47);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Oixviau','Eu Eleifend Nec Limited',51);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Voheejv','Odio Sagittis Semper Associates',48);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Corpemo','Senectus Et Company',24);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Joebulx','Laoreet Foundation',79);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Aixaioe','Dapibus Rutrum Inc.',36);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Numiicy','Libero Associates',64);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Xizdoeu','Mollis LLC',75);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Ciaiakv','Semper Industries',87);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Ienfohb','Eu Tellus Phasellus Institute',14);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Lesqiof','Fringilla Donec Feugiat Ltd',82);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Fotheln','Nulla Eget Inc.',22);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Aecdaoj','Blandit Corp.',61);
INSERT INTO "teams" (short_name,full_name,league) VALUES ('Cazwomm','Massa LLC',30);
